const PDFDocument = require('pdfkit');

const COLORS = {
  navy:   '#1A3560',
  gold:   '#C9A227',
  gray:   '#6B7280',
  light:  '#F1F5F9',
  border: '#E2E8F0',
  black:  '#111827',
  green:  '#16A34A',
  red:    '#DC2626',
};

function drawLine(doc, y, color = COLORS.border) {
  doc.moveTo(50, y).lineTo(545, y).strokeColor(color).lineWidth(0.5).stroke();
}

function drawTextHeader(doc, tenantSettings, companyName) {
  const lh = tenantSettings?.letterhead || {};
  const displayName    = lh.companyName || companyName || 'Company Name';
  const displayPhone   = lh.phone       || tenantSettings?.phone   || '';
  const displayEmail   = lh.email       || tenantSettings?.email   || '';
  const displayAddress = lh.address     || tenantSettings?.address || '';

  doc.rect(0, 0, 595, 95).fill(COLORS.navy);
  doc.fillColor('#fff').fontSize(20).font('Helvetica-Bold').text(displayName, 50, 22, { width: 300 });

  const contactLines = [displayPhone, displayEmail, displayAddress].filter(Boolean);
  doc.fillColor('rgba(255,255,255,0.75)').fontSize(8).font('Helvetica');
  contactLines.forEach((line, i) => {
    doc.text(line, 350, 22 + (i * 13), { width: 200, align: 'right' });
  });

  doc.rect(0, 95, 595, 4).fill(COLORS.gold);
  doc.fillColor(COLORS.black);
  return 99; // headerBottom Y
}

/**
 * Load a letterhead into a Buffer. Handles both a base64 data URL (legacy, from
 * before Cloudinary uploads worked) and an https URL (current — uploads now
 * store a Cloudinary link, which doc.image() cannot read directly).
 */
async function loadLetterheadBuffer(src) {
  if (!src || typeof src !== 'string') return null;
  try {
    if (src.startsWith('data:')) {
      return Buffer.from(src.replace(/^data:image\/\w+;base64,/, ''), 'base64');
    }
    if (/^https?:\/\//i.test(src)) {
      const res = await fetch(src);
      if (!res.ok) return null;
      return Buffer.from(await res.arrayBuffer());
    }
  } catch (e) {
    console.error('[PDF] Letterhead load failed:', e.message);
  }
  return null;
}

// Nexusora branding appears on trial workspaces only — paying tenants get a
// clean document.
function drawFooter(doc, pageNum, showBranding = true) {
  const y = 780;
  drawLine(doc, y);
  doc.fillColor(COLORS.gray).fontSize(8).font('Helvetica');
  if (showBranding) {
    doc.text('Generated by Nexusora Books · Powered by Nexusora Technologies', 50, y + 8, { align: 'left' });
  }
  doc.text(`Page ${pageNum}`, 50, y + 8, { align: 'right', width: 495 });
}

// ─── Customer Statement ───────────────────────────────────────────────────────
async function generateCustomerStatement({ customer, invoices, tenantSettings, companyName, plan }) {
  const lhBuffer = await loadLetterheadBuffer(tenantSettings?.letterheadImage);
  const showBranding = (plan || 'trial') === 'trial';
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header — use image if available, else text
      let hY = 99; // default headerBottom
      if (lhBuffer) {
        try {
          doc.image(lhBuffer, 0, 0, { width: 595 });
          doc.rect(0, 124, 595, 4).fill(COLORS.gold);
          doc.fillColor(COLORS.black);
          hY = 128;
        } catch (e) {
          hY = drawTextHeader(doc, tenantSettings, companyName);
        }
      } else {
        hY = drawTextHeader(doc, tenantSettings, companyName);
      }

      const sY = hY + 16; // content start Y

      // Title
      doc.fillColor(COLORS.navy).fontSize(16).font('Helvetica-Bold').text('CUSTOMER STATEMENT', 50, sY);
      const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
      doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica').text(`As at ${today}`, 50, sY + 22);
      drawLine(doc, sY + 38);

      // Customer details
      doc.fillColor(COLORS.navy).fontSize(10).font('Helvetica-Bold').text('CUSTOMER DETAILS', 50, sY + 48);
      doc.fillColor(COLORS.black).fontSize(10).font('Helvetica-Bold').text(customer.name, 50, sY + 64);
      doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica');
      if (customer.email)   doc.text(customer.email,   50, sY + 78);
      if (customer.phone)   doc.text(customer.phone,   50, sY + 90);
      if (customer.address) doc.text(customer.address, 50, sY + 102);
      if (customer.taxId)   doc.text(`TIN: ${customer.taxId}`, 50, sY + 114);

      // Summary box
      const totalInvoiced = invoices.reduce((s, i) => s + (i.total || 0), 0);
      const totalPaid     = invoices.reduce((s, i) => s + (i.amountPaid || 0), 0);
      const outstanding   = customer.outstandingBalance || (totalInvoiced - totalPaid);

      doc.rect(350, sY + 42, 195, 90).fill(COLORS.light).stroke(COLORS.border);
      doc.fillColor(COLORS.navy).fontSize(9).font('Helvetica-Bold').text('ACCOUNT SUMMARY', 362, sY + 52);
      doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica');
      doc.text('Total Invoiced:', 362, sY + 68);
      doc.text('Total Paid:',     362, sY + 82);
      doc.text('Outstanding:',    362, sY + 96);
      doc.fillColor(COLORS.black).font('Helvetica-Bold');
      doc.text(`GHS ${totalInvoiced.toFixed(2)}`, 430, sY + 68, { width: 105, align: 'right' });
      doc.text(`GHS ${totalPaid.toFixed(2)}`,     430, sY + 82, { width: 105, align: 'right' });
      doc.fillColor(outstanding > 0 ? COLORS.red : COLORS.green).fontSize(10);
      doc.text(`GHS ${outstanding.toFixed(2)}`,   430, sY + 96, { width: 105, align: 'right' });

      // Invoice table
      let y = sY + 150;
      doc.fillColor(COLORS.navy).fontSize(11).font('Helvetica-Bold').text('INVOICE HISTORY', 50, y);
      y += 18;

      doc.rect(50, y, 495, 22).fill(COLORS.navy);
      doc.fillColor('#fff').fontSize(8).font('Helvetica-Bold');
      // Re-spaced: BALANCE (right-aligned) used to run into STATUS, printing
      // both on top of each other.
      const cols = { num: 50, date: 115, due: 180, total: 245, paid: 315, balance: 385, status: 460 };
      doc.text('INVOICE #', cols.num + 4,    y + 7);
      doc.text('DATE',       cols.date + 4,  y + 7);
      doc.text('DUE DATE',   cols.due + 4,   y + 7);
      doc.text('TOTAL',      cols.total + 4, y + 7, { width: 60, align: 'right' });
      doc.text('PAID',       cols.paid + 4,  y + 7, { width: 60, align: 'right' });
      doc.text('BALANCE',    cols.balance + 4, y + 7, { width: 60, align: 'right' });
      doc.text('STATUS',     cols.status + 4, y + 7);
      y += 22;

      invoices.forEach((inv, i) => {
        if (y > 720) {
          drawFooter(doc, 1, showBranding);
          doc.addPage();
          drawTextHeader(doc, tenantSettings, companyName);
          y = 120;
        }
        doc.rect(50, y, 495, 20).fill(i % 2 === 0 ? '#fff' : COLORS.light);
        doc.fillColor(COLORS.black).fontSize(8).font('Helvetica');
        const statusColor = inv.status === 'paid' ? COLORS.green : inv.status === 'overdue' ? COLORS.red : COLORS.gold;

        doc.text(inv.invoiceNumber || '—', cols.num + 4, y + 6);
        doc.text(new Date(inv.date).toLocaleDateString('en-GB'),    cols.date + 4, y + 6);
        doc.text(new Date(inv.dueDate).toLocaleDateString('en-GB'), cols.due + 4,  y + 6);
        doc.text(`GHS ${(inv.total || 0).toFixed(2)}`,      cols.total + 4,   y + 6, { width: 60, align: 'right' });
        doc.text(`GHS ${(inv.amountPaid || 0).toFixed(2)}`, cols.paid + 4,    y + 6, { width: 60, align: 'right' });
        doc.fillColor(inv.balance > 0 ? COLORS.red : COLORS.green);
        doc.text(`GHS ${(inv.balance || 0).toFixed(2)}`,    cols.balance + 4, y + 6, { width: 60, align: 'right' });
        doc.fillColor(statusColor);
        doc.text((inv.status || '').toUpperCase(), cols.status + 4, y + 6);
        y += 20;
      });

      if (invoices.length === 0) {
        doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica').text('No invoices found.', 50, y + 10);
        y += 30;
      }

      drawLine(doc, y + 2, COLORS.navy);
      y += 8;
      doc.fillColor(COLORS.navy).fontSize(9).font('Helvetica-Bold');
      doc.text('TOTAL', 50, y + 4);
      doc.text(`GHS ${totalInvoiced.toFixed(2)}`, cols.total + 4,   y + 4, { width: 70, align: 'right' });
      doc.text(`GHS ${totalPaid.toFixed(2)}`,     cols.paid + 4,    y + 4, { width: 70, align: 'right' });
      doc.fillColor(outstanding > 0 ? COLORS.red : COLORS.green);
      doc.text(`GHS ${outstanding.toFixed(2)}`,   cols.balance + 4, y + 4, { width: 70, align: 'right' });

      drawFooter(doc, 1, showBranding);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// ─── Invoice PDF ──────────────────────────────────────────────────────────────
async function generateInvoicePDF({ invoice, customer, tenantSettings, companyName, plan }) {
  const lhBuffer = await loadLetterheadBuffer(tenantSettings?.letterheadImage);
  const showBranding = (plan || 'trial') === 'trial';  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let hY = 99;
      if (lhBuffer) {
        try {
          doc.image(lhBuffer, 0, 0, { width: 595 });
          doc.rect(0, 124, 595, 4).fill(COLORS.gold);
          doc.fillColor(COLORS.black);
          hY = 128;
        } catch (e) {
          console.error('[PDF] Letterhead embed failed:', e.message);
          hY = drawTextHeader(doc, tenantSettings, companyName);
        }
      } else {
        hY = drawTextHeader(doc, tenantSettings, companyName);
      }

      const sY = hY + 16;

      // Invoice title + number
      doc.fillColor(COLORS.navy).fontSize(22).font('Helvetica-Bold').text('INVOICE', 50, sY);
      doc.fillColor(COLORS.gold).fontSize(14).font('Helvetica-Bold').text(invoice.invoiceNumber, 50, sY + 28);

      // Status badge
      const statusColors = { paid: COLORS.green, overdue: COLORS.red, sent: COLORS.gold, draft: COLORS.gray };
      const sc = statusColors[invoice.status] || COLORS.gray;
      doc.rect(400, sY, 145, 28).fill(sc + '20').stroke(sc);
      doc.fillColor(sc).fontSize(11).font('Helvetica-Bold')
        .text((invoice.status || '').toUpperCase(), 402, sY + 8, { width: 141, align: 'center' });

      drawLine(doc, sY + 44);

      // Bill To
      doc.fillColor(COLORS.navy).fontSize(9).font('Helvetica-Bold').text('BILL TO', 50, sY + 54);
      doc.fillColor(COLORS.black).fontSize(11).font('Helvetica-Bold').text(customer?.name || '—', 50, sY + 68);
      doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica');
      if (customer?.email)   doc.text(customer.email,   50, sY + 82);
      if (customer?.phone)   doc.text(customer.phone,   50, sY + 94);
      if (customer?.address) doc.text(customer.address, 50, sY + 106);
      if (customer?.taxId)   doc.text(`TIN: ${customer.taxId}`, 50, sY + 118);

      // Invoice details right
      const details = [
        ['Invoice Date:', new Date(invoice.date).toLocaleDateString('en-GB')],
        ['Due Date:',     new Date(invoice.dueDate).toLocaleDateString('en-GB')],
        ['Currency:',     'GHS (Ghana Cedis)'],
      ];
      doc.fillColor(COLORS.navy).fontSize(9).font('Helvetica-Bold').text('INVOICE DETAILS', 350, sY + 54);
      details.forEach(([label, value], i) => {
        doc.fillColor(COLORS.gray).font('Helvetica').text(label, 350, sY + 68 + (i * 14));
        doc.fillColor(COLORS.black).font('Helvetica-Bold').text(value, 420, sY + 68 + (i * 14), { width: 125, align: 'right' });
      });

      // Line items
      let y = sY + 150;
      doc.fillColor(COLORS.navy).fontSize(11).font('Helvetica-Bold').text('ITEMS', 50, y);
      y += 16;

      doc.rect(50, y, 495, 22).fill(COLORS.navy);
      doc.fillColor('#fff').fontSize(8).font('Helvetica-Bold');
      doc.text('DESCRIPTION', 58,  y + 7);
      doc.text('QTY',         330, y + 7, { width: 50,  align: 'right' });
      doc.text('UNIT PRICE',  385, y + 7, { width: 70,  align: 'right' });
      doc.text('AMOUNT',      460, y + 7, { width: 80,  align: 'right' });
      y += 22;

      (invoice.lines || []).forEach((line, i) => {
        doc.rect(50, y, 495, 20).fill(i % 2 === 0 ? '#fff' : COLORS.light);
        doc.fillColor(COLORS.black).fontSize(9).font('Helvetica');
        doc.text(line.description || '—',             58,  y + 6, { width: 268 });
        doc.text(String(line.quantity || 0),           330, y + 6, { width: 50,  align: 'right' });
        doc.text(`GHS ${(line.unitPrice || 0).toFixed(2)}`, 385, y + 6, { width: 70,  align: 'right' });
        doc.text(`GHS ${(line.amount   || 0).toFixed(2)}`,  460, y + 6, { width: 80,  align: 'right' });
        y += 20;
      });

      drawLine(doc, y + 4, COLORS.border);
      y += 14;

      const totalsX = 350, valX = 460, valW = 80;

      [
        ['Subtotal:', invoice.subtotal || 0],
        invoice.taxRate ? [`VAT (${invoice.taxRate}%):`, invoice.taxAmount || 0] : null,
      ].filter(Boolean).forEach(([label, value]) => {
        doc.fillColor(COLORS.gray).fontSize(9).font('Helvetica').text(label, totalsX, y);
        doc.fillColor(COLORS.black).font('Helvetica-Bold').text(`GHS ${value.toFixed(2)}`, valX, y, { width: valW, align: 'right' });
        y += 16;
      });

      drawLine(doc, y, COLORS.navy);
      y += 6;
      doc.fillColor(COLORS.navy).fontSize(12).font('Helvetica-Bold').text('TOTAL:', totalsX, y);
      doc.fontSize(14).text(`GHS ${(invoice.total || 0).toFixed(2)}`, valX, y - 2, { width: valW, align: 'right' });
      y += 20;

      if (invoice.amountPaid > 0) {
        doc.fillColor(COLORS.green).fontSize(9).font('Helvetica').text('Amount Paid:', totalsX, y);
        doc.font('Helvetica-Bold').text(`GHS ${(invoice.amountPaid || 0).toFixed(2)}`, valX, y, { width: valW, align: 'right' });
        y += 16;
        doc.fillColor(COLORS.red).text('Balance Due:', totalsX, y);
        doc.font('Helvetica-Bold').text(`GHS ${(invoice.balance || 0).toFixed(2)}`, valX, y, { width: valW, align: 'right' });
      }

      if (invoice.notes) {
        y += 30;
        doc.fillColor(COLORS.navy).fontSize(9).font('Helvetica-Bold').text('NOTES:', 50, y);
        doc.fillColor(COLORS.gray).font('Helvetica').text(invoice.notes, 50, y + 14, { width: 495 });
      }

      drawFooter(doc, 1, showBranding);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateCustomerStatement, generateInvoicePDF };